namespace: dev

name: comment-service

labels:
  app: comment-service

containers:
  name: comment-service
  image:
    repository: cuhoang112/comment-service
    tag: 9cee337
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 500m
  http_port: 3004
  tcp_port: 4004

service:
  type: ClusterIP
  ports:
    port: 4004
    targetPort: 4004

configmap:
  name: comment-service
  data:
    msa_port: "4004"
    msa_host: "0.0.0.0"
    article_service_host: "article-service"
    article_service_port: "4003"
    http_port: "3004"
    model_url: "http://predict-service:8000/predict"
    api_version: v1

secret:
  name: comment-service
