services:
  postgres:
    image: postgres:17.4-bookworm
    environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB_NAME}
    env_file:
    - .env
    ports:
      - '5432:5432'
    volumes:
    - postgres:/var/lib/postgresql/data
    restart: always
volumes:
  postgres:
    driver: local
