services:
  postgres:
    image: postgres:17.4-bookworm
    environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
    - .env
    ports:
      - '5432:5432'
    volumes:
    - postgres:/var/lib/postgresql/data
    - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql 
    restart: always
  mongodb:
    image: mongo:latest
    environment:
     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
     MONGO_INITDB_DATABASE: ${MONGO_DB}
    env_file:
    - .env
    ports:
      - '27017:27017'
    volumes:
    - mongodb:/data/db
    restart: always
volumes:
  postgres:
    driver: local
  mongodb:
    driver: local
