apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.configmap.name}}
data:
  MSA_PORT: {{ .Values.configmap.data.msa_port | quote }}
  MSA_HOST: {{ .Values.configmap.data.msa_host | quote }}
  ARTICLE_SERVICE_HOST: {{ .Values.configmap.data.article_service_host | quote }}
  ARTICLE_SERVICE_PORT: {{ .Values.configmap.data.article_service_port | quote }}
  HTTP_PORT: {{ .Values.configmap.data.http_port | quote }}
  MODEL_URL: {{ .Values.configmap.data.model_url | quote }}
  API_VERSION: {{ .Values.configmap.data.api_version | quote }}