apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.configmap.name }}
data:
  MSA_PORT: {{ .Values.configmap.data.msa_port | quote }}
  MSA_HOST: {{ .Values.configmap.data.msa_host | quote }}
  HTTP_PORT: {{ .Values.configmap.data.http_port | quote }}
  API_VERSION: {{ .Values.configmap.data.api_version | quote }}