---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: article-service
  namespace: dev
spec:
  encryptedData:
    MONGODB_URI: AgAVCwFRoqOXdqaSwiAgxIxu6+HKREPX1hzES5Q0YNXpJbWu+Wwr9C5aByDEMZ5u3DeK12Oyj4surdr8k8Emn0vY4yDBTEk7trLmnXKIAGMGlB+WrWAM5ZKiadVG9+UwZbKPFG5DnSZ82rW/Xa2sbaZJDbPodQ8QpoddJCY9vr8wQcgxbtJxbjalD6QAe/moIA2060dK5xebRjhal0c1yWBuljsNBIIJzAHA7gRS9tITAtTUCEkFA/ASrLKMPLkIvpyodILgswjH2bLq7xjNJ/+qUdR1USZohXUwGTii7q5PZc/wPTUjVEkWKRq4zH8vZuT2UkDhmcEm8s9vJea0oXWBmKGiT9GQFjHXfSAJmfAj5qW4JyU+H0RfL8SfLb2lzn9OqkM2ANqRmRt+IxjMEigB1M59r/tQaCX3RFQh3E9nx/jD9d2Kt9aCC1/dXrsTn16Zx9r3tCVWv59jyHtl6Rdm8ICMycaxKfENOrr6V3fZ2ZNdw7ztkQbNyRcKi/Emi9MR5tV7zrJk/pfMNBaswJTjc8XLVbxCvIJtoIO2pxLwKlvwJzre+ImWDdJxZWzI0o0F9op5jrUyN7ILfUUU64nU2VpoXmcOn2n+MSs0GPNMZ96fZSQkb9wIo7b0GC2coUpnbH2e2ENew8MAG0bhtnbAj9dOyZYdyUj8QLeBr7Fm0cU/dZlHNjaQLfhe2tK9c6wUXa5IQTJsVfKXTnYo6tkqh0AmmER9Sf+SOB//eY4QgjZbf6mlykGnmjdAxExmUokl19C1THbtSdVvXUWpR8/psbjrQfdF3PymxUz1usgq8j5sQOrap13L4igOQwdq3h4Rum6kYqJ0MZ2jOpL7ryFOMYZK+kHDR4GMY1BW1D+DpX1Z+VkKIAZqi8xu6mgah5eWMj5kyTXCGUmqVKA9MyAjcFmXxQKDq8cRhS4KElDWNor98lYAGQufKNBrwPKTEkxwe0uisFbLO72ht106HsxMUABYgWY+FX2wCwvP4fgYSf4U2ITVy9Hm8DwzZT2eN8fFEycC+TH7jzDNFz/1MUSegRyAqcnwQ//Rol0YYA==
  template:
    metadata:
      creationTimestamp: null
      name: article-service
      namespace: dev
    type: Opaque
