apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
      - name: {{ .Values.containers.name }}
        image: "{{ .Values.containers.image.repository }}:{{ .Values.containers.image.tag }}"
        resources:
          requests:
            memory: {{ .Values.containers.resources.requests.memory }}
            cpu: {{ .Values.containers.resources.requests.cpu }}
          limits:
            memory: {{ .Values.containers.resources.limits.memory }}
            cpu: {{ .Values.containers.resources.limits.cpu }}
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        ports:
        - name: http
          containerPort: {{ .Values.containers.http_port }}