namespace: dev

name: auth-service

labels:
  app: auth-service

containers:
  name: auth-service
  image:
    repository: cuhoang112/auth-service
    tag: 9cee337
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 500m
  http_port: 3002
  tcp_port: 4002

service:
  type: ClusterIP
  ports:
    port: 4002
    targetPort: 4002

configmap:
  name: auth-service
  data:
    postgres_host: auth-service-db-postgresql
    postgres_port: 5432
    postgres_db_name: auth-service
    msa_port: 4002
    msa_host: 0.0.0.0
    user_service_host: user-service
    user_service_port: 4001
    http_port: 3002
    api_version: v1

secret:
  name: auth-service
