---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service
  namespace: dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCnD8B3y4WuevKDWVBVRnEOX2brSsufW61MDtWKrbNd3Ut7Yz9MHw9GmwwbCuRUGdMRKSAFFVQ0hUC6NbmXAWm8J7hKgZX2MUs/xqC8AiqEhYv/Xc+YUhtGybop/GBo/OaV/nhJx43UxfHIM7Y0u+jObb2NqBi2p81f5Lxoug6jAppXRrEOPzpnt5eReuO0kVXSCgjI/tdCy2DUJJF1UYBQWvfsOQGHcxhwX1N3q289qEOIiwUCzNbiDjW6LA8Qk2MkZX1wdrpI0KKA9/6iJGcJuAHZZN6FIwywjdqnVVnWt7bqm8ebvGzw7E2Zfay8+mlLsPDqkHJlUJRUCP+O1kequazHvuWSmbulRBx4gJa5pB5AVQQL2O7W7EvnxaXGs+wF4uHh7nfShSwTnF70oWraGS0fSi6LbvC6pHvMs6N+Uohi7dVfP2LgE1c/7cDxXA4qScIk1Z1hiXujQfNjusoH7py5HP2dvwvj+uOraJO5PNB94Id7CQbK53vdZkPiFrjNn9wasu9BeZW21zi/ke+GXUa4gobPaAsDZYcKQgOcTAuC+eP4IZgU8+IVxzgjXlHltOwSI66dqjeol793ZAgKtG6MoYv3zypnT0qXBj5KLzIj3Ywi7cTsCJVcKUn6H5plcr3wm87iKaRwKvqkX9hDiP74S/Eblkufny2pLq3uGGl1M78gZ+u6VNhXAwMBXry2SUE9YsPMzCNU
    POSTGRES_USER: AgA3VsNQBn28ZsQ2HADy9Br4KyXke2GDTmuG+DlHfXobpn3WrDlqPUMFGbp9wfh7dSYrxb8DR60LxvCEn8jEoTcWq/qV7ifb2IEKHaVvI/+oigkUw+xNx2UGoO6fpF6QQvJe7AzinfTlh8bbp79ZykHeAgGRK8LB5c1iwYWTanJfQmjyPM5EpHWfjfYiLln7tF9mAaWN06kQe4idXQ7woGQJalbWkWNWeqxTVKYDg9rIWnkYiVsYG7I9gEyLfsq7hEW4/1yrpaKz3vGcT4DQ5Ecw+isCSUWh1NWY119lc1dpWH2iNVUe/x7ReMzSQ6h+KlPv0mDjLi+/c+LgPxfiu85OFMQKs9gAuk2dHK68k1eHi1wkywqzi54rGnfkc5ETZLuMlX7HwSJ8GyQVa/eH/44HrjzbynddB9h0TLDUxwu7UOxYKoiMUmDVUZAKqYurz4OPJ4ivRFStkURHd/4UUCzpEW4GFrJaaKwT/x+QvJ9ll5c4gns9ZQfOf5dYVHwDirwmc8rnxPiYMGVeSZbQDim2zdEitBE+m5SNH0EixkGjCLaaABbh9hoaDtzhcR5cVrKzCDivcn2wU9L1Ck11O8H41tq+kBCIj7ROXMLMUMaOBM3Sqvz3vUE0I/DRbv6U4Uvt9FIXVhTKSHwaNmWsXoKnYnO/olxraYVv2TO+AoZFitRtETcWOouwJJr/9iQv213WDu7wUOg24nBN
  template:
    metadata:
      creationTimestamp: null
      name: user-service
      namespace: dev
    type: Opaque
