apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: predict-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Friederi/IE403.P21-NLPmodel.git
    targetRevision: main
    path: helm-charts/predict-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
