namespace: dev

name: user-service

labels:
  app: user-service

containers:
  name: user-service
  image:
    repository: cuhoang112/user-service
    tag: 9cee337
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 500m
  http_port: 3001
  tcp_port: 4001

service:
  type: ClusterIP
  ports:
    port: 4001
    targetPort: 4001

configmap:
  name: user-service
  data:
    postgres_host: user-service-db-postgresql
    postgres_port: 5432
    postgres_db_name: user-service
    msa_port: 4001
    msa_host: 0.0.0.0
    http_port: 3001
    api_version: v1

secret:
  name: user-service
