name: ci-api-gateway
on:
  workflow_dispatch:

  push:
    branches:
      - feature/**
    paths:
      - .github/workflows/**
  
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**


jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.2.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
          args: >
            -Dsonar.projectKey=Cu-Hoang_simplenews
            -Dsonar.organization=ng
            -Dsonar.exclusions=apps/user-service,apps/article-service,apps/auth-service,apps/comment-service,apps/user-service-e2e,apps/api-gateway-e2e,apps/article-service-e2e,apps/auth-service-e2e,apps/comment-service-e2e

  docker:
    needs: sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@v0.3.0
        with:
          scan-type: 'fs'
          scan-ref: './apps/api-gateway'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Get SHA 
        id: get_sha
        run: |
          SHA=$(git log -n 1 --pretty=format:%h -- apps/api-gateway)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.dockerfile
          build-args: |
            SERVICE=api-gateway
            HTTP_PORT=3000
          push: false
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ steps.get_sha.outputs.sha }}
      
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@v0.3.0
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ steps.get_sha.outputs.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'