name: ci
on:
  push:
  pull_request:
    branches: [ dev ]
    paths:
    - 'apps/**'
    - 'package.json'
    - 'package-lock.json'
    - '.github/workflows/ci.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.14.0']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version}}
        cache: 'npm'

    - name: Check Node.js version
      run: |
        node_version=$(node --version)
        required_version=$(node -p "require('./package.json').engines.node")
        if [[ ! "$node_version" == "$required_version" ]]; then
          echo "Error: Node.js version $node_version does not match required version $required_version"
          exit 1
        fi

    - name: Print node/npm versions
      id: versions
      run: |
        node_ver=$(node --version)
        npm_ver=$(npm --version)

        echo "Node: ${node_ver:1}"
        echo "NPM: $npm_ver"

        echo "node_version=${node_ver:1}" >> $GITHUB_OUTPUT
        echo "npm_version=$npm_ver" >> $GITHUB_OUTPUT

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint --fix

    - name: Check security vulnerabilities
      run: npm audit

    - name: Build project
      run: npm run build
